/* confdefs.h */
#define PACKAGE_NAME ""
#define PACKAGE_TARNAME ""
#define PACKAGE_VERSION ""
#define PACKAGE_STRING ""
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL ""
#define HAVE_POLL 1
#define HAVE_SENDFILE 1
#define HAVE_KQUEUE 1
#define HAVE_EXECINFO 1
#define HAVE_DAEMON 1
#define HAVE_MKOSTEMP 1
#define HAVE_PTRACE 1
#define HAVE_RWLOCK 1
#define HAVE_PCRE 1
#define HAVE_POSTGRESQL 1
#define SW_HAVE_BROTLI 1
#define SW_HAVE_ZLIB 1
#define HAVE_REUSEPORT 1
#define HAVE_VALGRIND 1
#define HAVE_CLOCK_GETTIME 1
#define SW_USE_HTTP2 1
