name: ext-swoole-linux

on: [push, pull_request]

jobs:
  build:
    name: Test on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
        matrix:
          os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: phpize && ./configure --enable-sockets --enable-mysqlnd --enable-http2 --enable-openssl --enable-debug-log
    - name: make
      run: make
