name: Pecl Package

on: [ push, pull_request ]

jobs:
  pecl-package:
    if: "!contains(github.event.head_commit.message, '--filter=') || contains(github.event.head_commit.message, '[unit]')"
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.1', '8.2', '8.3', '8.4', '8.1-zts', '8.2-zts', '8.3-zts', '8.4-zts' ]
        os: [ ubuntu-24.04, ubuntu-24.04-arm ]
    name: ${{ matrix.php }}-${{ matrix.os }}-pecl
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
          coverage: none
      - name: Show machine information
        run: |
          php -v
          echo "`git log -20 --pretty --oneline`"
          echo "`git log -10 --stat --pretty --oneline`"
      - name: Run pecl-install.sh
        run: |
          sudo ${{runner.workspace}}/swoole-src/scripts/pecl-install.sh
