name: run-swoole-test

on: [push, pull_request]

jobs:
  run-swoole-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [7.2, 7.3, 7.4, 8.0, 8.1]
    steps:
    - uses: actions/checkout@v1
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: "${{ matrix.php }}"
    - name: Show machine information
      run: |
        date
        env
        uname -a
        ulimit -a
        php -v
        php --ini
        ls -al
        pwd
        echo "`git log -20 --pretty --oneline`"
        echo "`git log -10 --stat --pretty --oneline`"
    - name: Run pecl-install.sh
      run: |
        sudo ${{runner.workspace}}/swoole-src/travis/pecl-install.sh
    - name: Run simple-compile-on-github.sh
      run: |
        sudo ${{runner.workspace}}/swoole-src/travis/simple-compile-on-github.sh
    - name: Run Swoole test
      run: |
        ${{runner.workspace}}/swoole-src/travis/route.sh
