name: Windows tests
run-name: Windows tests for ${{ inputs.tag || github.ref_name }}
on: [push, pull_request]

jobs:
  windows:
    runs-on: ubuntu-latest
    name: Windows Build
    steps:
      - name: Build
        run: |
          gh workflow run php.yml -R swoole/windows-builder -f tag="php-8.4"
